// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zttrmbxkddrgzcxtvmlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0dHJtYnhrZGRyZ3pjeHR2bWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjY1NzAsImV4cCI6MjA2NTIwMjU3MH0.ebwu6PPFVE9a6TBE-OMOD-Ua7oZ3PDa4YdZKaF3bmlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);